export const weekInterList = [{
    index: 0,
    isChecked: false,
    weekday: "周一",
    week: 2,
    startTime: "00:00",
    endTime: "23:59",
    err: false
}, {
    index: 1,
    isChecked: false,
    weekday: "周二",
    week: 3,
    startTime: "00:00",
    endTime: "23:59",
    err: false
}, {
    index: 2,
    isChecked: false,
    weekday: "周三",
    week: 4,
    startTime: "00:00",
    endTime: "23:59",
    err: false
}, {
    index: 3,
    isChecked: false,
    weekday: "周四",
    week: 5,
    startTime: "00:00",
    endTime: "23:59",
    err: false
}, {
    index: 4,
    isChecked: false,
    weekday: "周五",
    week: 6,
    startTime: "00:00",
    endTime: "23:59",
    err: false
}, {
    index: 5,
    isChecked: false,
    weekday: "周六",
    week: 7,
    startTime: "00:00",
    endTime: "23:59",
    err: false
}, {
    index: 6,
    isChecked: false,
    weekday: "周日",
    week: 1,
    startTime: "00:00",
    endTime: "23:59",
    err: false,
}]