//支持申办的车牌颜色
export const PLATE_COLOR = [
    {
      color:'/assets/static/plate-blue.png',
      select_color:'/assets/static/plate-blue-selete.png',
      id:0
    },
    {
      color:'/assets/static/plate-yellow.png',
      select_color:'/assets/static/plate-yellow-selete.png',
      id:1
    },
    {
      color:'/assets/static/plate-black.png',
      select_color:'/assets/static/plate-black-selete.png',
      id:2
    },
    {
      color:'/assets/static/plate-green.png',
      select_color:'/assets/static/plate-green-selete.png',
      id:4
    }
]