Component({
    properties:{
        //提示的标题
        title:{
            type:String,
            value:'标题'
        },
        //提示的内容
        content:{
            type:String, 
            value:'内容'
        },
        //取消按钮的文字
        cancel_text:{
            type:String,
            value:'取消',
        },
        //确认按钮的文字
        confirm_text:{
            type:String,
            value:'确定',
        },
        //是否显示取消按钮
        show_cancel:{
            type:Boolean,
            value:true,
        },
        //取消按钮的文字颜色
        cancel_color:{
            type:String,
            value:'#303030',
        },
        //确认按钮的文字颜色
        confirm_color:{
            type:String,
            value:'#303030',
        },
        custom_content:{
            type:Boolean,
            value:false
        },
        is_show_modal:{
            type:Boolean,
            value:false
        },
        type:{
            type:Number,
            value:0//modal 内容显示样式 0:代表纯文本 1:代表冲红内容 
        },
        redaction:{//冲红数据
            type:Object
        },
        custom:{//自定义
            type:Boolean,
            value:false
        }
    },
    methods:{
        //用户点击了确定按钮
        confirm:function(){
            this.triggerEvent('confirm', {}) 
        },
        //用户点击了取消
        cancel:function(){
            this.setData({is_show_modal:false});
        }
    }
});