export const coupons = [
    {
        id:1,
        name:"中国银行",
        area_name:"山东",
        area_code:"370000",
        logo_url:"https://oilmag.etcsd.com.cn/oilcoreserver/static//resource/refurling-gold-yc.png",
        desc_list:["1、如果所选非油商品不足提货券金额，不找零；超出部分需在便利店内补足差价","2、本券仅限购买山东壳牌加油站便利店商品(烟草、清仓及特价商品除外)"],
        sub_activity_url:"https://home.firefoxchina.cn/?from=start"
    },
    {
        id:2,
        name:"中国招商银行",
        area_name:"全国",
        area_code:"000000",
        logo_url:"https://oilmag.etcsd.com.cn/oilcoreserver/static//resource/refurling-gold-yc.png",
        desc_list:["1、如果所选非油商品不足提货券金额，不找零；超出部分需在便利店内补足差价"],
        sub_activity_url:"https://home.firefoxchina.cn/?from=start"
    },
    {
        id:3,
        name:"中国建设银行",
        area_name:"山东,石家庄市",
        area_code:"370000,130100",
        logo_url:"https://oilmag.etcsd.com.cn/oilcoreserver/static//resource/refurling-gold-yc.png",
        desc_list:[],
        sub_activity_url:"https://home.firefoxchina.cn/?from=start"
    }
]